Likes and replies
mzt-tang/twitter_copy pull request #7
Opened 2021-12-05 22:49 UTC by mzt-tang

Implemented Like model + controller and Reply mode + controller.
The React front-end don't look great but works as a temporary stand in till better layout design is implemented with the avatar.

2021-12-08 22:10 UTC, lucy-dement requested changes
I know this a bit annoying but would you mind finding someone who's more familiar with react to review those parts. You'll get much better feedback that way.

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/likes_controller.rb
> +      return
Does this ever actually get hit, or are you blocking it in the UI?
Cause if you are blocking it then raising an error would be better because to get to this point somethings gone wrong.

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/likes_controller.rb
> +    if @like.valid?
It's rails convention in this sort of scenario to use `build` and `save` instead of `create` and valid`.
```
@like = @post.likes.build(user_id: current_user.id)

if @like.save
```
There's not really any functional difference but it's just more common.

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/likes_controller.rb
> +      Like.where(user_id: current_user.id, post_id: params[:post_id]).destroy_all
You're running the same query twice here which is a bit inefficient.

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +    # current_user.posts.order(created_at: :desc)
You might want to remove the comment

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +    post = Post.all.order(created_at: :desc)
This should probably be named `posts` cause there's more than one

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +    if post
This won't work how you think it does. If the post has errors then the `create!` will raise an error so the if statement will never get run.

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +      render json: post.errors.full_messages
If the post doesn't exist what are you getting the errors from?

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +    post = current_user.posts.create!(post_params);
Also naming this the same thing as a method is just confusing.

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +    params.require(:post).permit(:tweet)
Awesome. Strong params are good 👍

2021-12-08 22:10 UTC, lucy-dement commented on app/controllers/api/v2/replies_controller.rb
> +    if @reply.valid?
Same comment here about `create` and `valid`

2021-12-08 22:10 UTC, lucy-dement commented on app/models/like.rb
> +  belongs_to :post, counter_cache: true
Why are you caching the counter?
As a performance improvement it seems a bit premature. You don't know what sort of load this feature is going to get, so adding this cache at the moment is making your schema more complicated while solving a problem you don't have yet.

2021-12-08 22:10 UTC, lucy-dement commented on app/models/post.rb
> +end
Your indentation in this file is a bit weird.

2021-12-08 22:10 UTC, lucy-dement commented on config/routes.rb
> +        resources :replies, only: [:index, :create, :show, :destroy] do
Nice use of `resources` it definitely helps group routes and makes it easier to navigate.

2021-12-08 22:10 UTC, lucy-dement commented on db/migrate/20211126012045_add_user_to_posts.rb
> +    add_reference :posts, :user, null: false, foreign_key: true
Ok so weird rails thing, it doesn't play nice with `foreign_key`. So when creating a reference like this set `foreign_key: false`. I know that seems weird cause obviously it is being used as a foreign key but rails will still treat it as one anyway, it just won't be set as one in the database.

2021-12-08 22:10 UTC, lucy-dement commented on db/migrate/20211126012940_create_likes.rb
> +      t.references :post, null: false, foreign_key: true
Same here too

2021-12-08 22:10 UTC, lucy-dement commented on db/migrate/20211128210527_add_likes_count_to_posts.rb
> +      t.integer :likes_count, null: false, default: 0
Can you add timestamps to your new tables just so you get in the habit of doing it(in spacewaffle we have to add them to every table the data warehouse relies on them).

2021-12-12 19:13 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +    if post
Err you haven't changed this michael

2021-12-12 19:13 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +      render json: post.errors.full_messages
Or this

2021-12-12 20:16 UTC, mzt-tang commented on app/controllers/api/v2/posts_controller.rb
> +    if post
changed to .build now :)

2021-12-12 21:59 UTC, lucy-dement commented on app/controllers/api/v2/posts_controller.rb
> +      render json: @post.errors.full_messages
@post will be nil here so it was break

2021-12-13 01:33 UTC, lucy-dement approved these changes
The backend looks good to me 😄

2021-12-13 03:04 UTC, KatieFrenchOptimal reviewed
Hi hi

I just wanna say this is some really great work - you should be super proud of it! I can't wait to see it at a Friday demo (maybe this week??? 😉)

Nothing is really worth changing IMO unless you really wanted to but I was more trying to leave some comments about some things to think about when you start playing around in the app after this project.

Just an extra note, there were a few missing semi-colons and empty lines where they don't need to be. I would recommend using a linting tool for your code editor that picks this stuff up so you don't have to worry about it when you put it up for review 🙂

Great work!! 👏 👏 👏 👏

2021-12-13 03:04 UTC, KatieFrenchOptimal commented on app/assets/stylesheets/navbar.scss
> +  font-size: large;
This is fine for your project, but we wouldn't use this in the app. Instead of using `large` we would give it a rem size

2021-12-13 03:04 UTC, KatieFrenchOptimal commented on app/javascript/components/Post.jsx
> +    if (await postBelongsToUser()) {
I think that instead of using async/await I would recommend you use a javascript Promise. I don't expect you to change over to it now but for future reference [here's a link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) to a doc about them! You can also google the differences between them if ya need

2021-12-13 03:04 UTC, KatieFrenchOptimal commented on app/javascript/components/Post.jsx
> +      if (postLike !== undefined) {
`if postLike is not undefined` feels a _little_ confusing. I feel like it would make more sense phrased as `if postLike is true`. This would look like `if (postLike) {`, which is a lot easier on the eye than `if (postLike !== undefined) {`. Disclaimer, in saying this I'm not 100%  sure if this even works in this case! It depends on what value comes out so don't change on my account, just something worth keeping in mind for future work! (I can see you've done some other good rules around the rest of you project so I'm assuming you need this one to be specific like that)

2021-12-13 03:04 UTC, KatieFrenchOptimal commented on app/javascript/components/Post.jsx
> +      <div className="icon-container">
I think the naming for this class should be more meaningful as it contains a lot more than just icons.

2021-12-13 03:04 UTC, KatieFrenchOptimal commented on app/javascript/components/replies.scss
> +}
There are a few places where you have classes that have repeated content in them, you could always think about how you could reuse them a bit better. A more general name like what you had in another file that was called `list-unstyled` and then reuse that instead.

2021-12-13 03:04 UTC, KatieFrenchOptimal commented on app/javascript/components/replymodal.scss
> +}
I think this would have been a good opportunity to utilise the BEM scss format. It's a good mindest to start getting into! If this helps, the css would have looked something like this...

```
.modal {
   &--body {
     width: 80%;
     margin: auto;
   }

   &--post {
     color: black;
     border-bottom: 4px solid black;
   }

   &--action-buttons {
     position: relative;
     left: 5px;
     display: flex;
     flex-direction: row;
     justify-content: flex-end;
     gap: 10px;
   }
}
```

2021-12-13 22:04 UTC, merged